require_relative "../app/models/user.rb"
require_relative "../app/models/event.rb"
require_relative "../app/models/category.rb"
# User.create(username: "LumpySpacePrincess", email: "wattheglob@gmail.com", password: "mylumps")
# User.create(username: "JakeTheDog", email: "jakeNladyforever@gmail.com", password: "ilovemylady")
# User.create(username: "Finnz123", email: "thefinnator@gmail.com", password: "flame_princess")
# User.create(username: "MarcelineVQ", email: "vampirequeen@gmail.com", password: "timeisanillusion")
# User.create(username: "LizLaffitte", email: "liz@gmail.com", password: "complicated")
# Event.create(name: "Super Bowl 2021", start_datetime: "2021-02-07T12:00", location: "Tampa, Florida", details: "Super Bowl LV will be held in Raymond James Stadium.", user_id: 2, )
# Category.create(name: "Sports")
# Category.create(name: "Music")
# Category.create(name: "Food")
# Category.create(name: "Camp")
# Category.create(name: "Kids")
# Category.create(name: "Holiday")
# Event.create(name: "Cooking Class", start_datetime: "2020-02-07T12:00", location: "Jacksonville, Florida", details: "This class is for absolute beginners.", user_id: 5 )
# Event.create(name: "Paradise Miami (MMW 2020)", start_datetime: "2020-03-06T09:00",end_datetime: "2020-03-08T17:00", location: "Orlando, FL", details: "Podfest Expo is a community of people who are interested in and passionate about sharing their voice and message with the world through the powerful mediums of audio and video. We’re proud to unite as many people as possible to learn, get inspired, and grow better together.", user_id: 1 )
# Event.create(name: "Muddy Princess", start_datetime: "2020-04-05T07:00", end_datetime: "2020-04-05T16:00", location: "Punta Gorda, FL", details: "Muddy Princess is an outdoor 5km (3.1 mile) obstacle mud run for women - and women ONLY!", user_id: 1, category_ids: ["1"])
# Event.create(name: "Dessert Wars", start_datetime: "2020-03-05T15:00", end_datetime: "2020-03-05T18:00", location: "Miami, FL", details: "Dessert Wars is a celebration of the “foodie” lifestyle, featuring dessert vendors vying for the title of Dessert Champion. The event features a wide array of desserts ranging from cupcakes, cookies, ice cream and doughnuts.", user_id: 3, category_ids: ["3"])
# Event.create(name: "Orlando Taco Festival", start_datetime: "2020-02-05T14:00", end_datetime: "2020-03-01T20:00", location: "Orlando, FL", details: "Taco Heaven Awaits with over 25 restaurants and food truck serving up their signature tacos, complete with tequila & margarita bars and more.", user_id: 3, category_ids: ["3"])
# Event.create(name: "Confection Affection", start_datetime: "2020-03-14T13:00", end_datetime: "2020-03-14T16:00", location: "Tampa, FL", details: "Tampa Bay Beer Week 2020 just got more interesting... On Saturday, March 14th we will be throwing a joint party & you're gonna wanna be there!", user_id: 3, category_ids: ["3"])